export const initialState = {
  log: [
    "=== CIPHER DETECTIVE TERMINAL INITIALIZED ===",
    "",
    "Welcome, Detective Alex Cipher.",
    "",
    "You've been called to investigate a series of mysterious incidents in Neo Ashridge.",
    "Your reputation for solving complex puzzles and riddles precedes you.",
    " ",
    "",
    "A new case file has been uploaded to your terminal...",
        " ",
    "",
    "Type 'help' to see available commands or 'investigate' to begin.",
  ],
  input: "",
  location: "apartment",
  health: 100,
  inventory: [],
  progress: 0,
  caseId: "cipher-murders",
  solved: false,
  events: {},
};
